#! /bin/sh
#
#             _       _                                   __ _       
#            | |     | |                                 / _(_)      
# _ __   ___ | |_   _| |__   __ _ _ __    ___ ___  _ __ | |_ _  __ _ 
#| '_ \ / _ \| | | | | '_ \ / _` | '__|  / __/ _ \| '_ \|  _| |/ _` |
#| |_) | (_) | | |_| | |_) | (_| | |    | (_| (_) | | | | | | | (_| |
#| .__/ \___/|_|\__, |_.__/ \__,_|_|     \___\___/|_| |_|_| |_|\__, |
#| |             __/ |                                          __/ |
#|_|            |___/                                          |___/ 
#
# Polybar Configuration File
# https://github.com/polybar/polybar | https://polybar.github.io/

# Coded by: Darkstardevx [darkstardevx@gmail.com]
# https://github.com/darkstardevx/dotfiles/polybar/

[global/wm]
; Adjust the _NET_WM_STRUT_PARTIAL bottom value
;   Used for bottom aligned bars
margin-top = 0

; Adjust the _NET_WM_STRUT_PARTIAL top value
;   Used for top aligned bars
margin-bottom = 0

include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini

[settings]
; Reload upon receiving XCB_RANDR_SCREEN_CHANGE_NOTIFY events
screenchange-reload = true
screenchange = true

; The throttle settings lets the eventloop swallow up til X events
; if they happen within Y millisecond after first event was received.
; This is done to prevent flood of update event.
;
; For example if 5 modules emit an update event at the same time, we really
; just care about the last one. But if we wait too long for events to swallow
; the bar would appear sluggish so we continue if timeout
; expires or limit is reached.
throttle-output = 5
throttle-output-for = 10

; @deprecated The setting is ignored since 3.5.0
; Time in milliseconds that the input handler will wait between processing events
throttle-input-for = 30

; Compositing operators
; @see: https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-operator-t
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

; Enables pseudo-transparency for the bar
; If set to true the bar can be transparent without a compositor.
pseudo-transparency = true

[bar/left-mybar]
monitor = ${env:MONITOR:HDMI-0}
width = 100%
height = 24
radius = 2.0
fixed-center = false
enable-ipc = true

background = ${xrdb:background:#222}
foreground = ${xrdb:foreground:#eeeeec}

line-size = 3
line-color = #f00

border-size = 4
border-color = #00000000

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 2

# See the Fonts wiki page for more details
# https://github.com/jaagr/polybar/wiki/Fonts

font-0 = fixed:pixelsize=7;1
font-1 = unifont:fontformat=truetype:size=7:antialias=false;0
font-2 = siji:pixelsize=7;1
font-3 = Noto Color Emoji:pixelsize=10:scale=8:style=Regular;2
font-4 = Roboto Mono:pixelsize=8:style=Regular:2
font-5 = Roboto Mono Medium:pixelsize=8:style=Regular:2
font-6 = UbuntuMono Nerd Font:size=10;2
font-7 = UbuntuMono Nerd Font:size=16;3
font-8 = Font Awesome 5 Free:style=Regular:pixelsize=8;1
font-9 = Font Awesome 5 Free:style=Solid:pixelsize=8;1
font-10 = Font Awesome 5 Brands:pixelsize=8;1
font-11 = Hack Nerd Font:style=Bold:pixelsize=10

modules-left = bspwm
modules-center = mpd
modules-right = pulseaudio-control memory cpu eth temp date

tray-position = right
tray-padding = 2
tray-background = #2e3436

wm-restack = bspwm
override-redirect = true

scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

cursor-click = pointer
cursor-scroll = ns-resize

[bar/right-mybar]
monitor = ${env:MONITOR:DVI-0}
width = 100%
height = 24
radius = 2.0
fixed-center = false
enable-ipc = true

background = ${xrdb:background:#222}
foreground = ${xrdb:foreground:#eeeeec}

line-size = 3
line-color = #f00

border-size = 4
border-color = #00000000

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 2

font-0 = fixed:pixelsize=7;1
font-1 = unifont:fontformat=truetype:size=7:antialias=false;0
font-2 = siji:pixelsize=7;1
font-3 = Noto Color Emoji:pixelsize=10:scale=8:style=Regular;2
font-4 = Roboto Mono,Roboto Mono Medium:pixelsize=8:style=Regular:2
font-5 = Font Awesome 5 Free:pixelsize:8:style:Regular:0

modules-left = bspwm
modules-center = spotify
modules-right = arch-aur-updates info-ssh-sessions filesystem wlan eth temp date powermenu

tray-padding = 2

wm-restack = bspwm
override-redirect = true

scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

cursor-click = pointer
cursor-scroll = ns-resize


