#! /bin/sh
# _                                                    __ _       
#| |                                                  / _(_)      
#| |__  ___ _ ____      ___ __ ___     ___ ___  _ __ | |_ _  __ _ 
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \   / __/ _ \| '_ \|  _| |/ _` |
#| |_) \__ \ |_) \ V  V /| | | | | | | (_| (_) | | | | | | | (_| |
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_|  \___\___/|_| |_|_| |_|\__, |
#          | |                                               __/ |
#          |_|                                              |___/ 
# Binary Space Partition Window Manager - Config File
# https://github.com/baskerville/bspwm
#
# Coded by:
# Darkstardevx [darkstardevx@gmail.com]
# https://github.com/darkstardevx/.dotfiles/bspwm/

# pgrep -x sxhkd > /dev/null || sxhkd &

# 1. Configuration
export BSPWM_SCRIPTS_DIR="$HOME/.config/bspwm/scripts/"

# 1A. Gnome Keyring Daemon
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh) export SSH_AUTH_SOCK

# 1B. Displays (monitors)
###This creates and names desktops for multiple monitors.
#workspaces_multimonitor &

# HDMI-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 476mm x 268mm
bspc monitor HDMI-0 -d $(seq 1 25)

# DVI-0 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 476mm x 268mm
bspc monitor DVI-0 -d $(seq 26 50)

bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true

# Display Resolution + Positioning (xrandr)
xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal --output DVI-0 --mode 1920x1080 --rotate normal --right-of HDMI-0 &

# 1C. Desktop layouts (tiled is the default)
#bspc desktop 22 -l monocle
#bspc desktop 23 -l monocle
#bspc desktop 24 -l monocle
#bspc desktop 25 -l monocle

# 1D. Other layouts (https://github.com/phenax/bsp-layout)
#bsp-layout set wide 25 --master-size 0.52
#bsp-layout set tall 24
#bsp-layout set even 23
#bsp-layout set tiled 22
#bsp-layout set monocle 21
#bsp-layout set rgrid 24


# 1E. External scripts (rules for windows)
bspc config external_rules_command "$HOME"/.config/bspwm/scripts/external_rules

# 2. Autostart

# Simple X Hotkey Daemon
killall sxhkd
sxhkd &

# Polybar
$HOME/.config/polybar/launch.sh

# Picom (Compositor)
killall picom
#compton --config ~/.config/picom/picom.conf &
picom --config ~/.config/picom/picom.conf --experimental-backends &

# Dunst (Notifications)
killall dunst
# $HOME/.config/dunst/dunstrc
/usr/bin/dunst &

# NetworkManager Applet
nm-applet &

# Pamac Manager
pamac-tray &

# Xfce4 Notes
killall xfce4-notes
xfce4-notes -d &

# Clipboard Manager (ClipIt)
killall clipit
clipit &

# Clipboard Manager (Greenclip)
killall greenclip
greenclip daemon &

# Guake Terminal
# killall guake
# guake &

# Cloud
killall megasync
megasync &

# Secure Chat
killall session
session &

# Screencasting
killall simplescreenrecorder
simplescreenrecorder &

# Vorta (BORG Backup GUI)
killall vorta
vorta &

# Wallpapers (nitrogen)
killall nitrogen
nitrogen --restore &

# Screensaver
killall xscreensaver
xscreensaver --no-splash &

# Hides mouse when you are not using it
unclutter &

# Power Manager Settings
killall xfce4-power-manager-settings
xfce4-power-manager-settings &

# Passwords
killall bitwarden
bitwarden &

# Audio
start-pulseaudio-x11 &

# VPN
#/opt/piavpn/bin/pia-client

# SOCKS 5
killall ss-qt5
ss-qt5 &

# Number Locker
numlockx &

# Bluetooth
# killall blueman-tray
# blueman-tray &

# Bluetooth
killall blueman-manager
blueman-manager &

# policykit-1-gnome
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# 3. Global Settings

# Border width and gaps between windows
border_width=5
#window_gap=5
bspc config border_width         0
bspc config window_gap           $border_width

# Padding
bspc config top_padding 25
bspc config bottom_padding 0
bspc config left_padding 1
bspc config right_padding 1

# Pointer options
bspc config focus_follows_mouse true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

# Pointer bindings
# Focus the window (or the monitor) under the pointer if the value isn’t none.
# bspc config click_to_focus button1

# Prevents apps from stealing focus
bspc config ignore_ewmh_focus true

# Split ratio for new windows
bspc config split_ratio          0.50

# Settings for manual splitting
bspc config auto_alternate true
bspc config auto_cancel true

# The insertion scheme used when the insertion point is in automatic mode. Accepts the following values: longest_side, alternate, spiral.
# bspc config automatic_scheme alternate

# If monacle layout, no border to windows
bspc config borderless_monocle true

# No gaps
bspc config gapless_monocle true

# Pseudo tiled
bspc config center_pseudo_tiled	true

# Preselect
#bspc config presel_feedback	true
#bspc config presel_feedback_color	#444444		# see 5. Color Settings
  
# 4. Mouse Settings
# Use mouse to resize, move and focus windows
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action4 focus

# 5. Color Settings
bspc config normal_frame_opacity 1.0
bspc config focused_frame_opacity 0.05
bspc config focused_border_color "#813d9c"		# Color of the border of a focused window of a focused monitor.
bspc config normal_border_color "#000000"		# Color of the border of an unfocused window.
#bspc config active_border_color "#bd93f9"		# Color of the border of a focused window of an unfocused monitor.
bspc config presel_border_color "#fc03d0"
bspc config urgent_border_color "#f50c0c"
bspc config focused_private_border_color "#1c71d8"
#bspc config presel_feedback_color "#6272a4"		# Color of the node --presel-{dir,ratio} message feedback area.
bspc config border_width 1

# 5.1 Global Colors (See Color Settings [5] Above)

# 5.2 Pywal
chmod +x ${HOME}/.cache/wal/colors.sh
source "${HOME}/.cache/wal/colors.sh"

#wal -R & # -R restores the last colorscheme that was in use.

# 6. Window Rules (workspaces)

# 6.1 Startup Rules (open applications on specific workspaces)
#bspc rule -a google-chrome state=tiled desktop='^1'
#bspc rule -a firefox state=tiled desktop='^2'
#bspc rule -a brave-bin state=tiled desktop='^3'

# 6.2 Pseudo Tiled Rules
bspc rule -a File-roller      pseudo_tiled=on focus=on
bspc rule -a Catfish 		  pseudo_tiled=on focus=on
#bspc rule -a nm-connection-editor pseudo_tiled=on focus=on
#bspc rule -a Skype            pseudo_tiled=on focus=on
#bspc rule -a Thunar pseudo_tiled=on focus=on

# 6.3 Tiled Rules
bspc rule -a Gedit state=tiled center=true
bspc rule -a Shotwell state=tiled center=true

# 6.4 Floating Rules
bspc rule -a Nm-connection-editor state=floating focus=on
bspc rule -a Pamac-manager state=floating rectangle=800x500+100+100 sticky=on
bspc rule -a rofi state=floating follow=on center=true
bspc rule -a Mousepad state=floating rectangle 900x600+100+100 center=true
bspc rule -a ReText state=floating center=true
bspc rule -a io.github.celluloid_player.Celluloid:* state=floating
bspc rule -a Termite state=floating rectangle=800x500+100+100 center=true
bspc rule -a kitty state=floating rectangle=800x500+100+100 center=true
bspc rule -a feh state=floating center=true
bspc rule -a Sxiv state=floating center=true
bspc rule -a vlc state=floating center=true
bspc rule -a Xfce4-dict state=floating center=true
bspc rule -a Xfce4-notes state=floating center=true
bspc rule -a Guake state=floating center=true
bspc rule -a Gcolor3 state=floating center=true
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Nitrogen state=floating center=true
bspc rule -a GParted state=floating center=true
bspc rule -a Postman state=floating center=true
bspc rule -a k3b state=floating center=true
bspc rule -a Brasero state=floating center=true
bspc rule -a Audacious state=floating center=true
bspc rule -a Vorta state=floating rectangle 900x600+100+100 center=true
bspc rule -a Gparted state=floating center=true
bspc rule -a Pcmanfm state=floating rectangle=800x500+100+100 center=true
bspc rule -a Xscreensaver-demo state=floating center=true
bspc rule -a Remarkable state=floating center=true
bspc rule -a Spotify state=floating center=true
bspc rule -a Devede_ng.py state=floating center=true
bspc rule -a Youtube-dl-gui state=floating rectangle=800x500+100+100 center=true
bspc rule -a Mediainfo-gui state=floating center=true
bspc rule -a SimpleScreenRecorder state=floating center=true
bspc rule -a VirtualBox Manager state=floating center=true
bspc rule -a Devede_ng.py state=floating center=true
bspc rule -a Alacritty state=floating rectangle=800x500+100+100 center=true
bspc rule -a st-256color state=floating rectangle=800x500+100+100 center=true
bspc rule -a neovim state=floating rectangle=800x500+100+100 sticky=on
bspc rule -a Gvim state=floating rectangle=800x500+100+100 sticky=on
bspc rule -a xfce4-appfinder state=floating
bspc rule -a Filezilla state=floating rectangle=1400x1200+100+100 center=true
bspc rule -a Skype state=floating center=true
bspc rule -a Oomox state=floating center=true
bspc rule -a Gucharmap state=floating rectangle=800x500+100+100 sticky=on
bspc rule -a pamac-manager state=floating rectangle=800x500+100+100 sticky=on
bspc rule -a Termius state=floating rectangle 900x600+100+100 center=true
bspc rule -a shadowsocks-qt5 state=floating rectangle 900x600+100+100 center=true
bspc rule -a Timeshift-gtk state=floating rectangle=800x500+100+100 center=true
bspc rule -a Blueman-manager state=floating rectangle=800x500+100+100 center=true
bspc rule -a Bitwarden state=floating rectangle=800x500+100+100 sticky=on
bspc rule -a xdotool-gui state=floating rectangle=800x500+100+100 center=true
bspc rule -a Xfce4-appfinder state=floating center=true
bspc rule -a Pavucontrol state=floating rectangle=800x500+100+100 center=true
bspc rule -a Cherrytree state=floating rectangle=1000x1000+100+100 center=true
bspc rule -a Boostnote state=floating rectangle=1200x1000+100+100 center=true
bspc rule -a Psensor state=floating rectangle=800x500+100+100 center=true
bspc rule -a Joplin state=floating rectangle=1000x1000+100+100 center=true
bspc rule -a Gnome-system-monitor state=floating rectangle=800x500+100+100 center=true
bspc rule -a simplenote:Simplenote state=floating rectangle=800x500+100+100 center=true
bspc rule -a Grsync state=floating rectangle 900x600+100+100 center=true
bspc rule -a zoom state=floating rectangle 900x800+100+100 center=true
bspc rule -a session state=floating rectangle 900x600+100+100 center=true
bspc rule -a megasync state=floating rectangle 800x600+100+100 center=true
bspc rule -a gsmartcontrol state=floating rectangle 800x600+100+100 center=true
bspc rule -a gufw.py state=floating rectangle 900x800+100+100 center=true
