#!/bin/sh
#
# _                                             _                        _              _           
#| |                                           | |                      | |            | |          
#| |__  ___ _ ____      ___ __ ___     _____  _| |_ ___ _ __ _ __   __ _| |  _ __ _   _| | ___  ___ 
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \   / _ \ \/ / __/ _ \ '__| '_ \ / _` | | | '__| | | | |/ _ \/ __|
#| |_) \__ \ |_) \ V  V /| | | | | | |  __/>  <| ||  __/ |  | | | | (_| | | | |  | |_| | |  __/\__ \
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_|  \___/_/\_\\__\___|_|  |_| |_|\__,_|_| |_|   \__,_|_|\___||___/
#          | |                                                                                      
#          |_|                                                                                      
# bspwm external rules
# custom script

# Coded by:
# Darkstardevx [darkstardevx@gmail.com]
# https://github.com/darkstardevx/dotfiles/bspwm/scripts/

# BSPWM RULES
window=$1
class=$2
instance=$3
title=$(xdotool getwindowname $window)

case $class in
  [Cc]elluloid|[Gg]color3|[Mm]pv|[Mm]Player|[Gg]picview|[Aa]randr|[Gg]alculator|[Ff]ont-manager|[Ss]kype|[Xx]fce4-appfinder|[Xx]fce4-about|[Gg]pick|[Cc]alc|[Pp]avucontrol|[Vv]lc|[Ff]eh|[Rr]istretto|[Ee]vince|scratchpad)
  echo "state = floating"
  echo "center = on"
  ;;
  Gimp)
   echo "desktop = ^20"
   ;;
esac

case $title in
  scratchpad)
    echo "state = floating"
    ;;
esac

# vim:ft=sh

